# Generated by Django 2.1.2 on 2018-11-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileForm',
            new_name='Profiles',
        ),
    ]
