# Generated by Django 2.1.2 on 2018-11-08 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profiles_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
